jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set VERSION environment variable
        id: version
        run: echo "VERSION=$(($(cat version.txt) + 1))" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          echo "Using image version: $VERSION"
          docker pull docker.io/hummingbirddock/supermariogitopsproject:$VERSION
          docker save -o supermariolatestdockerimage.tar docker.io/hummingbirddock/supermariogitopsproject:$VERSION
     
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '1'
          severity: 'CRITICAL,HIGH'